### ISSUE TITLE
Consultant and end session

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#13]
When ending session with a consultant choice Please have the app go back to scan with new session

**Comment by hriziya** [comment]
Fixed

**Comment by rafdelre** [comment]
yes it now works but it keeps in memory the previosly chosen consultant

**Comment by hriziya** [comment]
"but it keeps in memory the previosly chosen consultant"

Can you explain ?

**Comment by sergiostrampelli** [comment]
You should use Session.read to know the consultant selected for the session.

**Comment by hriziya** [comment]
Done.

**Comment by rafdelre** [comment]
Sergio we should check if in menu option, consultant choice is correct
thankyou

**Comment by sergiostrampelli** [comment]
Yes, from the server side the choice is correct.
The App, just after Session.update, calls Session.read: this is useless because the response of Session.update has the same content.

But the user interface is messy: after selection I cannot see if the consultant that was selected, please have the app stay on this page (consultant) ONLY when from menu

**Comment by hriziya** [comment]
Fixed

**Comment by rafdelre** [comment]
Not fixed

When choosing consultant from menu, it does not show the choice until you exit... WHY?
please debug

Try scanning a qr code box (bagno1) 

http://demo.youppers.com/box/list?store=762d6fdb-aba8-11e4-b4aa-0cc47a127a14

after that please
then choose consultant from menu

the choice is correctly sent to server with session update BUT the app does not show the choice.

**Comment by rafdelre** [comment]
Session update has to be sent when we click on the consultant.

This is also happening in END SESSION with consultant.

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
Ok this is fine.
We need a button in the screen where Consultants are when "Concludi e continua con il consulente" is chosen. A button that when pressed actually Ends session and goes back to scan with new session... it means the customer has ended the visit....

**Comment by hriziya** [comment]
Do you want to add new button ? or you want to use the "Edn Session" bottom right button on that page to mark end visit. ?

**Comment by rafdelre** [comment]
Yes
Thankyou

**Comment by hriziya** [comment]
which one I should use ?

A New button 
OR 
"End session" bottom right button ?

**Comment by rafdelre** [comment]
A new button in middle bottom of page 
Please have the conultant list scroll before button
I mean leave button fixed
Thankyou

**Comment by hriziya** [comment]
Done. Added new fixed positioned button on consultant list screen when End session.

**Comment by hriziya** [comment]
so, now when we select consultant it will session.update .. 
and only end session when click the newly added "End session" button

**Comment by rafdelre** [comment]
that sounds correct. Sergio please confirm
