### ISSUE TITLE
PDF in product detail

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#20]
In product detail please take away "settings" and "technical sheets" in bottom.

Please leave only DOCS in title (where now is brochure).

In DOCSyou will find a list of pdfs from api (as described in RPC doc Show Product Detail page) They have to be listed in vertical fashion one for every line with NAME on the right hand. 

When clicked it will open in the same manner as now.

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
Ok. There is the image attachments bug listed in other issue still

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
fixed
