### ISSUE TITLE
Product detail page selection

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#31]
On page 24 of json RPC document

After the call of Variant.list the options selected are the ones in the response (attribute_option > id is the Id of the selected option, while attribute_type_id is the id of the selector to which the option belongs)

Let me explain

when we arrive at the Product Detail page, this is represented by the data that you display
ok

BUT we need you to have the APP show SELECTED the options that are returned by the api. 
**attribute_option > id is the Id of the selected option, while attribute_type_id is the id of the selector to which the option belongs**

![image](https://cloud.githubusercontent.com/assets/11840209/7140407/5a935b68-e2cb-11e4-8507-d50ed56af82b.png)

**Comment by hriziya** [comment]
_we need you to have the APP show SELECTED the options that are returned by the api._

Which key I should consider to keep the attribute selected from API response ?

**Comment by sergiostrampelli** [comment]
These are the data exchanged between app and server for product with code 735619:

```
Request: {"id":"33","jsonrpc":"2.0","method":"Variant.read","params":{"variantId":"2bbbaa22-de93-11e4-b4aa-0cc47a127a14","sessionId":"c0513d7d-e380-11e4-b4aa-0cc47a127a14"}}
Response: {"jsonrpc":"2.0","result":{"id":"2bbbaa22-de93-11e4-b4aa-0cc47a127a14","product_collection":{"id":"64e06e0c-d7a1-11e4-b4aa-0cc47a127a14","name":"vetro","code":"VETRO","image":{"name":"neutra.png","enabled":false,"content_type":"image\/png","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_product\/0001\/01\/thumb_08fae5eb-de90-11e4-b4aa-0cc47a127a14_youppers_product_list.png","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_product\/0001\/01\/f9c988dc27a309f41e59d22914d3540ab7fb1b1c.png"}},"image":{"name":"avorio 735619.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_product\/0001\/01\/thumb_15d9fa12-de93-11e4-b4aa-0cc47a127a14_youppers_product_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_product\/0001\/01\/a7d43a93e012119802b5cc03115ca03779864266.jpeg"},"pdf_gallery":{"name":"FL CSM vetro neutra","enabled":true,"gallery_has_medias":[{"media":{"name":"vetro neutra1.pdf","enabled":false,"content_type":"application\/pdf","url":"http:\/\/demo.youppers.com\/uploads\/media\/..\/..\/bundles\/youpperscommon\/pdf-icon.png","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/pdf\/0001\/06\/87c3ccbfc3efbd6a2a389e67759e707ca850429d.pdf"},"position":1,"enabled":true}]},"variant_properties":[{"attribute_option":{"id":"31f97720-d787-11e4-b4aa-0cc47a127a14","name":"Colore","value":"02 avorio","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da"}},{"attribute_option":{"id":"22941955-d78a-11e4-b4aa-0cc47a127a14","name":"Dimensione","value":"Tessera 1,8x1,8","attribute_type_id":"61d6d6fe-b39f-11e4-82bd-0800273000da"}}],"product":{"name":"VETRO 02 AVORIO MOSAICO 4,5 mm","code":"735619","brand":{"name":"casamood","code":"CSM","company":{"name":"Florim","code":"FL","logo":{"name":"florim_logo.png","enabled":false,"content_type":"image\/png","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_company_logo\/0001\/01\/thumb_12_youppers_company_logo_list.png","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_company_logo\/0001\/01\/ddfb5a9bca0142b2a29c70d6bbd70e58a5b06927.png"}},"logo":{"name":"florim_log_casamood.png","enabled":false,"content_type":"image\/png","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_brand_logo\/0001\/01\/thumb_9_youppers_brand_logo_list.png","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_brand_logo\/0001\/01\/8fb1a88d68cbbbea4bebe3f68d20bc4f6ceb35b6.png"}}}},"id":"33"}
```

From the above response, these are the two options that must be selected (in bold the option and type ids):

{"attribute_option":{"id":"**_31f97720-d787-11e4-b4aa-0cc47a127a14**_","name":"Colore","value":"02 avorio","attribute_type_id":"**_ff007003-b2d9-11e4-8ef6-0800273000da**_"}},
{"attribute_option":{"id":"**_22941955-d78a-11e4-b4aa-0cc47a127a14**_","name":"Dimensione","value":"Tessera 1,8x1,8","attribute_type_id":"**_61d6d6fe-b39f-11e4-82bd-0800273000da**_"}}]

```
Request: {"id":"33","jsonrpc":"2.0","method":"Collection.read","params":{"collectionId":"64e06e0c-d7a1-11e4-b4aa-0cc47a127a14","sessionId":"c0513d7d-e380-11e4-b4aa-0cc47a127a14"}}
Response: {"jsonrpc":"2.0","result":{"id":"64e06e0c-d7a1-11e4-b4aa-0cc47a127a14","name":"vetro","code":"VETRO","image":{"name":"neutra.png","enabled":false,"content_type":"image\/png","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_product\/0001\/01\/thumb_08fae5eb-de90-11e4-b4aa-0cc47a127a14_youppers_product_list.png","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_product\/0001\/01\/f9c988dc27a309f41e59d22914d3540ab7fb1b1c.png"},"enabled":true,"brand":{"name":"casamood","code":"CSM","company":{"name":"Florim","code":"FL","logo":{"name":"florim_logo.png","enabled":false,"content_type":"image\/png","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_company_logo\/0001\/01\/thumb_12_youppers_company_logo_list.png","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_company_logo\/0001\/01\/ddfb5a9bca0142b2a29c70d6bbd70e58a5b06927.png"}},"logo":{"name":"florim_log_casamood.png","enabled":false,"content_type":"image\/png","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_brand_logo\/0001\/01\/thumb_9_youppers_brand_logo_list.png","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_brand_logo\/0001\/01\/8fb1a88d68cbbbea4bebe3f68d20bc4f6ceb35b6.png"}},"product_type":{"name":"Piastrella","code":"tile","product_attributes":[{"variant":true,"attribute_type":{"id":"ff007003-b2d9-11e4-8ef6-0800273000da","name":"Colore","code":"color"},"position":1},{"variant":true,"attribute_type":{"id":"25fdd180-b3ae-11e4-82bd-0800273000da","name":"Finitura","code":"FIN"},"position":2},{"variant":true,"attribute_type":{"id":"61d6d6fe-b39f-11e4-82bd-0800273000da","name":"Dimensione","code":"DIM"},"position":3},{"variant":false,"attribute_type":{"id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","name":"Decoro","code":"MIX"},"position":4}]},"pdf_gallery":{"name":"FL CSM vetro","enabled":true,"gallery_has_medias":[{"media":{"name":"cat_vetro1.pdf","enabled":false,"content_type":"application\/pdf","url":"http:\/\/demo.youppers.com\/uploads\/media\/..\/..\/bundles\/youpperscommon\/pdf-icon.png","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/pdf\/0001\/01\/0a111004f0ce2992611c7f4390a0f53275cc9bdf.pdf"},"position":1,"enabled":true}]}},"id":"33"}
```

From the above response, these are the three attributes type to be enabled (in bold the type id from Variant.read):

{"variant":true,"attribute_type":{"id":"**_ff007003-b2d9-11e4-8ef6-0800273000da**_","name":"Colore","code":"color"},"position":1},
{"variant":true,"attribute_type":{"id":"25fdd180-b3ae-11e4-82bd-0800273000da","name":"Finitura","code":"FIN"},"position":2},
{"variant":true,"attribute_type":{"id":"**_61d6d6fe-b39f-11e4-82bd-0800273000da**_","name":"Dimensione","code":"DIM"},"position":3},
{"variant":false,"attribute_type":{"id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","name":"Decoro","code":"MIX"},"position":4}]

Only the last one (that don't have variant=true) must be hidden because in variant read there is not an option for type "Decoro".

```
Request: {"id":"33","jsonrpc":"2.0","method":"Attributes.read","params":{"collectionId":"64e06e0c-d7a1-11e4-b4aa-0cc47a127a14","sessionId":"c0513d7d-e380-11e4-b4aa-0cc47a127a14"}}
Response: {"jsonrpc":"2.0","result":[{"id":"57f7a1af-b5ff-11e4-a918-0800273000da","name":"Rettificato","value":"No","attribute_type_id":"024527e9-b5ff-11e4-a918-0800273000da","position":2},{"id":"202efb81-d949-11e4-b4aa-0cc47a127a14","name":"Finitura","value":"Metal","attribute_type_id":"25fdd180-b3ae-11e4-82bd-0800273000da","position":10},{"id":"7f41c4bb-d940-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"melange light","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":1,"image":{"name":"melange light verde 725187.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_078a0834-d916-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/85cac51047a560aff93cb961c00b761b8870f560.jpeg"}},{"id":"7f41cd46-d940-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"melange dark","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":2,"image":{"name":"melange dark verde 724127.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_product\/0001\/01\/thumb_8faef63a-d7bb-11e4-b4aa-0cc47a127a14_youppers_product_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_product\/0001\/01\/7e10052af3329ab7c7c58997310d6c1ffca49298.jpeg"}},{"id":"7f41d626-d940-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"nuance","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":3,"image":{"name":"nuance grigio 725190.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_27ca4d26-d929-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/105304896f21f9b7c0f07ddda8f68ed74e8d5d21.jpeg"}},{"id":"7f41de5c-d940-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"transit","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":4,"image":{"name":"transit ghiaccio 725061.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_product\/0777\/67\/thumb_77666832-d7bf-11e4-b4aa-0cc47a127a14_youppers_product_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_product\/0777\/67\/332b2ee2ce54fe308c45464d231a56f2b7373fe3.jpeg"}},{"id":"428f41de-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"spring 01","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":5},{"id":"428f5394-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"spring 02","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":6},{"id":"428f5e71-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"spring 03","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":7},{"id":"428f688d-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"spring 04","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":8},{"id":"428f72c8-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"spring 05","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":9},{"id":"428f7cb4-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"spring 06","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":10},{"id":"428f8682-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"stripes 01","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":11},{"id":"428f90a2-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"stripes 02","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":12},{"id":"428f9a57-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"stripes 03","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":13},{"id":"428fa417-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"stripes 04","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":14},{"id":"428fad99-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"stripes 05","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":15},{"id":"428fb763-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"stripes 06","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":16},{"id":"428fc0ff-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"pattern 01","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":17},{"id":"428fcab4-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"pattern 02","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":18},{"id":"428fd443-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"pattern 03","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":19},{"id":"428fddbf-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"pattern 04","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":20},{"id":"428fe734-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"pattern 05","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":21},{"id":"428ff108-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"brocades 01","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":22},{"id":"428ffa9a-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"brocades 02","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":23},{"id":"4290044d-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"brocades 03","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":24},{"id":"42900e34-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"brocades 04","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":25},{"id":"429017f9-d94d-11e4-b4aa-0cc47a127a14","name":"Decoro","value":"brocades 05","attribute_type_id":"a53efe34-d93f-11e4-b4aa-0cc47a127a14","position":26},{"id":"565ea96a-dea3-11e4-b4aa-0cc47a127a14","name":"Colore","value":"07 carbone lux","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"carbone  lux 735631.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_54b955ba-dea3-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/d358ce9c69d2e10196867a741c976fc7472003ab.jpeg"}},{"id":"da1aa995-de97-11e4-b4aa-0cc47a127a14","name":"Colore","value":"02 avorio lux","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"avorio lux 735626.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_d7192bdd-de97-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/a09d8738cce432144a356eea2d809fe0b0d6720c.jpeg"}},{"id":"355fe90a-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"platino","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"platino.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/05\/thumb_4478c301-d788-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/05\/f4ebcfdbe9dc46bd2acab29d21bd6735eae2efce.jpeg"}},{"id":"31f96e14-d787-11e4-b4aa-0cc47a127a14","name":"Colore","value":"01 bianco","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"01 bianco.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_ac0cb10e-d787-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/425ca81921522d7947179bd7712920c40d6746cc.jpeg"}},{"id":"8f60e44a-dea1-11e4-b4aa-0cc47a127a14","name":"Colore","value":"05 cemento lux","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"cemento lux 735629.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_b70fce38-dea0-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/4bdab05e7a4a4a8ca910cecb827ba8f944886985.jpeg"}},{"id":"9f17dfe7-de94-11e4-b4aa-0cc47a127a14","name":"Colore","value":"01 bianco lux","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"bianco lux 735625.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_9c526a3d-de94-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/740c0417abee083277b2bdbc38ac38781dbfd7c2.jpeg"}},{"id":"6943e7b5-de9f-11e4-b4aa-0cc47a127a14","name":"Colore","value":"04 tortora lux","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"tortora lux 735628.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_679d72d2-de9f-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/00a34271af7f6fd2164acd26cd6da5d875d2bb1d.jpeg"}},{"id":"1ef60467-dec4-11e4-b4aa-0cc47a127a14","name":"Colore","value":"neutra melange scuro","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"neutra 735634.png","enabled":false,"content_type":"image\/png","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_1d1252bd-dec4-11e4-b4aa-0cc47a127a14_youppers_attribute_list.png","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/32d1673a001dc676f527075b96b9f24d2e2a75f4.png"}},{"id":"e10328b0-decb-11e4-b4aa-0cc47a127a14","name":"Colore","value":"neutra 01 bianco lux","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"bianco lux 515661.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_d072ed17-decb-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/b5d6711c50d840fc9948495bced8429d6e894002.jpeg"}},{"id":"3696b9d3-debf-11e4-b4aa-0cc47a127a14","name":"Colore","value":"neutra melange medio","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"neutra 765633.png","enabled":false,"content_type":"image\/png","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_2a527a29-debf-11e4-b4aa-0cc47a127a14_youppers_attribute_list.png","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/a98b1c349cb4181da9def5e25ac072f967c6735d.png"}},{"id":"967bb903-decd-11e4-b4aa-0cc47a127a14","name":"Colore","value":"bianco lux","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"bianco lux 515662.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/71\/thumb_7e4dafcc-decd-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/71\/8774a950fd11ad7653417b30a18e8b13fae8a354.jpeg"}},{"id":"e85c2b01-dea1-11e4-b4aa-0cc47a127a14","name":"Colore","value":"06 moka lux","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"moka lux 735630.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_e6389335-dea1-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/b2d0e83d2e3dd27b64046527908f1eeba3ec8141.jpeg"}},{"id":"fc37f3e3-debd-11e4-b4aa-0cc47a127a14","name":"Colore","value":"neutra melange","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"735632.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_d586bfce-debd-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/b8bac542ebee819861c2a2ce46d96a409135948d.jpeg"}},{"id":"37f12967-decd-11e4-b4aa-0cc47a127a14","name":"Colore","value":"neutra 01 bianco","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"bianco 515622.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_27c327cf-decd-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/7afc52570866b707102d9f6be6883605438ae9cf.jpeg"}},{"id":"271c194d-de9f-11e4-b4aa-0cc47a127a14","name":"Colore","value":"03 silver lux","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":1,"image":{"name":"silver lux 735627.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0252\/23\/thumb_25122669-de9f-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0252\/23\/129e8ab1ad56dc54ed7ccd50382656b848159169.jpeg"}},{"id":"8ad73717-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"giglio","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":2,"image":{"name":"giglio.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/07\/thumb_6848ccbb-d789-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/07\/4530e0ffd1320349134df4754fc7b353ced5adfe.jpeg"}},{"id":"355ff215-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"oro","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":2,"image":{"name":"oro.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_49b47ecd-d788-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/8d9405857dffce16ff1fdd685b8b0fcd133e4a05.jpeg"}},{"id":"31f97720-d787-11e4-b4aa-0cc47a127a14","name":"Colore","value":"02 avorio","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":2,"image":{"name":"02 avorio.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_b1a211b2-d787-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/49a6941867922f3166eac8535090718539439ea6.jpeg"}},{"id":"31f97f9f-d787-11e4-b4aa-0cc47a127a14","name":"Colore","value":"03 silver","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":3,"image":{"name":"03 silver.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_b6b6b06c-d787-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/ed98f650fe11e6dda503882e70a0a78e57b9b44c.jpeg"}},{"id":"e1c4f923-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"ghiaccio","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":4,"image":{"name":"ghiaccio.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_6ecd04e9-d789-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/719343fb8457d459918bfd113122bdb3c3f93a2d.jpeg"}},{"id":"31f98a14-d787-11e4-b4aa-0cc47a127a14","name":"Colore","value":"04 tortora","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":4,"image":{"name":"04 tortora.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_bcc8ef96-d787-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/01ade376e54d3c99066da8fba76c6419f525ea45.jpeg"}},{"id":"356002eb-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"cobalto","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":4,"image":{"name":"cobalto.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/06\/thumb_5821ed59-d788-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/06\/3411a747f8b8c35d0d62d857c830c7c429beffb1.jpeg"}},{"id":"31f992c6-d787-11e4-b4aa-0cc47a127a14","name":"Colore","value":"05 cemento","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":5,"image":{"name":"05 cemento.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_c24d980b-d787-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/9fa3790e32838c2c23eaa68c2f337c3333d135f2.jpeg"}},{"id":"e1c5035b-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"perla","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":5,"image":{"name":"perla.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_7a040f6f-d789-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/8105730c268517691c67f4e7689787db33bd3dd3.jpeg"}},{"id":"35600b19-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"iridescente","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":5,"image":{"name":"iridescente.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_5eea13a9-d788-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/4e5c423752c8796c09e10b93d9868897620a7208.jpeg"}},{"id":"e1c50b05-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"pietra","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":6,"image":{"name":"pietra.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_913cdb33-d789-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/527a12cf65a8ad12dff71c5725b42c3a7dd06253.jpeg"}},{"id":"a4e7356e-d787-11e4-b4aa-0cc47a127a14","name":"Colore","value":"06 moka","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":6,"image":{"name":"06 moka.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_ca46aa53-d787-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/6f88e643894b069c52520db4aef7ce1583feafd0.jpeg"}},{"id":"e1c51273-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"eucalipto","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":7,"image":{"name":"eucalipto.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_99d3b487-d789-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/5acdb4637eaf6b504af0b8b04c6c013296801c74.jpeg"}},{"id":"a4e74461-d787-11e4-b4aa-0cc47a127a14","name":"Colore","value":"07 carbone","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":7,"image":{"name":"07 carbone.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_d27b9cd2-d787-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/6af9b3bb584e38d3dd6314fc1bad556ab901e890.jpeg"}},{"id":"e1c519c5-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"iris","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":8,"image":{"name":"iris.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_a29d6fe2-d789-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/cdeccc1db590b4f8723a45ca41d65e0a6d2cbb08.jpeg"}},{"id":"e1c52111-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"muschio","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":9,"image":{"name":"muschio.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_a9f656de-d789-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/bb42ebc0d8a5826312ea83352e946619c6ca4625.jpeg"}},{"id":"e1c52855-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"salvia","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":10,"image":{"name":"salvia.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_b365b7fb-d789-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/ec995697d6229cf3f1485afd597eb2ab35b4171f.jpeg"}},{"id":"e1c52f87-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"viola","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":11,"image":{"name":"viola.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_bd9d3ce6-d789-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/d21e601235274434d46178758b0ae020d480f632.jpeg"}},{"id":"e1c536e3-d788-11e4-b4aa-0cc47a127a14","name":"Colore","value":"mosto","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":12,"image":{"name":"mosto.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_cb18d831-d789-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/8147468325ee94aa0014d4daafcdd1186ef2c426.jpeg"}},{"id":"a3fb3262-d7b0-11e4-b4aa-0cc47a127a14","name":"Colore","value":"cielo","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":13,"image":{"name":"colore cielo.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_a0204b9c-d7b0-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/6e227ccec098fdda060b7c91cf12220f3bf0ec26.jpeg"}},{"id":"b387c1c6-d7b1-11e4-b4aa-0cc47a127a14","name":"Colore","value":"lavanda","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":14,"image":{"name":"colore lavanda.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_029bd349-d7b1-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/66ec04fe0bf0c3a0e05cda4526eac3dfe1964c9d.jpeg"}},{"id":"b387cdae-d7b1-11e4-b4aa-0cc47a127a14","name":"Colore","value":"ribes","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":15,"image":{"name":"colore ribes.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_2c3ce0dd-d7b1-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/f6e81dfaa58d26ed7b78e455ffe0854cfe8c3871.jpeg"}},{"id":"b387d721-d7b1-11e4-b4aa-0cc47a127a14","name":"Colore","value":"peonia","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":16,"image":{"name":"colore peonia.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/09\/thumb_8349d7d8-d7b1-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/09\/c0bb7e713dade91554812f2cb1a76651ee897d84.jpeg"}},{"id":"b387e228-d7b1-11e4-b4aa-0cc47a127a14","name":"Colore","value":"malva","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":17,"image":{"name":"colore malva.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_affffc73-d7b1-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/3160c60f4722d2bd5edb5c195ccf06de5f1afaa8.jpeg"}},{"id":"279577a1-d7b2-11e4-b4aa-0cc47a127a14","name":"Colore","value":"acqua","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":18,"image":{"name":"colore acqua.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_24d27a5d-d7b2-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/6093b9795c63f9d276ecafa1557074f5057de4e8.jpeg"}},{"id":"299b88d7-d7b8-11e4-b4aa-0cc47a127a14","name":"Colore","value":"grigio","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":19,"image":{"name":"melange light grigio 725185.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_a2db0ade-d916-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/adee99a01e2d046d44cbf0ff53e5eba3bff8c448.jpeg"}},{"id":"299b9eb8-d7b8-11e4-b4aa-0cc47a127a14","name":"Colore","value":"azzurro","attribute_type_id":"ff007003-b2d9-11e4-8ef6-0800273000da","position":21,"image":{"name":"melange light azzurro 725188.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/09\/thumb_8675cf4a-d916-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/09\/b44e27e7e34d042455b5c15adcbc31924c06c6de.jpeg"}},{"id":"22941955-d78a-11e4-b4aa-0cc47a127a14","name":"Dimensione","value":"Tessera 1,8x1,8","attribute_type_id":"61d6d6fe-b39f-11e4-82bd-0800273000da","position":4,"image":{"name":"mosaico_1_8x1_8-30x30_dec@2x.png","enabled":false,"content_type":"image\/png","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/-9223372036854775807\/-9223372036854775807\/thumb_31e5397c-d78a-11e4-b4aa-0cc47a127a14_youppers_attribute_list.png","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/-9223372036854775807\/-9223372036854775807\/e1f9faca1e22bbee65c68cc66307d30a059fe24d.png"}},{"id":"8d50255b-ddff-11e4-b4aa-0cc47a127a14","name":"Dimensione","value":"Listello Dritto","attribute_type_id":"61d6d6fe-b39f-11e4-82bd-0800273000da","position":5,"image":{"name":"listello dritto.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/08\/thumb_7999f34a-de03-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/08\/d210645f4990d5e69902764754e8f046d6ddd231.jpeg"}},{"id":"8c82e1dc-d6e4-11e4-b4aa-0cc47a127a14","name":"Dimensione","value":"Listello Sfalsato","attribute_type_id":"61d6d6fe-b39f-11e4-82bd-0800273000da","position":6,"image":{"name":"modulo_listello_sfalsato-21x40_dec.png","enabled":false,"content_type":"image\/png","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_8a59dea2-d6e4-11e4-b4aa-0cc47a127a14_youppers_attribute_list.png","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/f1c058d25583b28a0b408cf9970a3bcdb88fe18d.png"}}],"id":"33"}
```

From the above response, these are the two options to be selected (in bold the attribute id and type id from variant read):

{"id":"**_31f97720-d787-11e4-b4aa-0cc47a127a14**_","name":"Colore","value":"02 avorio","attribute_type_id":"**_ff007003-b2d9-11e4-8ef6-0800273000da**_","position":2,"image":{"name":"02 avorio.jpg","enabled":false,"content_type":"image\/jpeg","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/thumb_b1a211b2-d787-11e4-b4aa-0cc47a127a14_youppers_attribute_list.jpeg","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/0001\/01\/49a6941867922f3166eac8535090718539439ea6.jpeg"}}
{"id":"**_22941955-d78a-11e4-b4aa-0cc47a127a14**_","name":"Dimensione","value":"Tessera 1,8x1,8","attribute_type_id":"**_61d6d6fe-b39f-11e4-82bd-0800273000da**_","position":4,"image":{"name":"mosaico_1_8x1_8-30x30_dec@2x.png","enabled":false,"content_type":"image\/png","url":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/-9223372036854775807\/-9223372036854775807\/thumb_31e5397c-d78a-11e4-b4aa-0cc47a127a14_youppers_attribute_list.png","url.reference":"http:\/\/demo.youppers.com\/uploads\/media\/youppers_attribute\/-9223372036854775807\/-9223372036854775807\/e1f9faca1e22bbee65c68cc66307d30a059fe24d.png"}}

```
Request: {"id":"33","jsonrpc":"2.0","method":"Item.list","params":{"variantId":"2bbbaa22-de93-11e4-b4aa-0cc47a127a14","sessionId":"c0513d7d-e380-11e4-b4aa-0cc47a127a14"}}
Response: {"jsonrpc":"2.0","result":[],"id":"33"}
```

**Comment by rafdelre** [comment]
Practically, a product has Variants and Options. Imagine a car where you have a product Model (BMW 320).
Now lets imagine you choose this product from list. Remember that product BMW320 in product list is the actual CAR present in the Showroom. And it obviously has a COLOR (BLUE) and it is a StationWagon.

Now if we click on this row (product) CAR bmw320 blue stationwagon, we access the Product Detail Page.

On top we have the photograph of the car, the name, the model the code....
In the center part of the product detail page (the scrollable items)
first row we could have these 3 options (of same type---- same line)

StationWagon  -  Coupe   -   Sedan

In our case, the option selected IS STATIONWAGON

is it clear up to now?

on the next row will be color

BLUE - RED - WHITE

In our case BLUE is selected

Then we might have
GAS Version or ELECTRICAL powered

Now if the customer clicks on COUPE
Coupe might not have BLUE so youppers should tell us that there are NO variants. CORRECT! and this is working.

If we DESELECT BLUE, and then click on COUPE we have a LIST of all COUPES. This is working. Lets click on one of the RED COUPE and we show page of the selected MODEL. This works.

NOW:
In the COUPE page you have icons for STATIONWAGON, COUPE and SEDAN. Right?
COUPE IS SELECTED NOW. Ok? AND RED is selected
IF you click on Stationwagon, (BMW makes a stationwagon that is RED), finally we will have a refresh page and SHOW the RED BMW Stationwagon!!!!
this is not working...
thank you

**Comment by hriziya** [comment]
Ok. I made a fix now, this should work as expected.  sending you APK in next few mins

**Comment by rafdelre** [comment]
this looks good
sergio ?

**Comment by rafdelre** [comment]
I think that it is not refreshing if there is only variant

**Comment by rafdelre** [comment]
try searching K193701
and you have correctly the product
then click to enter the product detail
AND it correctly selects and shows Piatto Doccia and 70x4x140

NOW try selecting 70x4x100
this is not working because it should REFRESH and show product k193501

REALLY URGENT

**Comment by hriziya** [comment]
Fixed. I've sent you updated APK

**Comment by rafdelre** [comment]
Thank you Hitesh
It works
It still does not keep the choices.

Why does it say 1.0.9?
Yesterday it was 1.0.10?
Today should be 1.0.11

This has to be coherent
Thankyou

**Comment by rafdelre** [comment]
have a look at #47 this is very urgent
thankyou
