### ISSUE TITLE
Select Option in detail

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#46]
Please make the selected square around option a little thicker as is in images please

We cannot distinguish select option

thankyou

**Comment by sergiostrampelli** [comment]
![image](https://cloud.githubusercontent.com/assets/9050752/7200176/a8adb704-e4fa-11e4-8695-f4dac4104eb8.png)

**Comment by hriziya** [comment]
Done. set thickness to 5 (was 2).

**Comment by rafdelre** [comment]
Please use bigger thickness and change to RED as the red in y of youppers logo. thankyou

**Comment by rafdelre** [comment]
Hitesh the icons are still wrong size
we have some that are 80 and some 90 in details
could you make them all 80?
even the selected?
thankyou

**Comment by hriziya** [comment]
Can you give me example of wrong icon size ? or may be a product code to search ?

**Comment by rafdelre** [comment]
Well any detail of any product that has more than one size or color

We have the icons that should all be 80 px 
Instead the selected one is different
If you dont see it i will send you screenshot
Thankyou

**Comment by hriziya** [comment]
Yes please send screenshot so that I don't misunderstood changes

**Comment by rafdelre** [comment]
![screenshot_2015-05-04-08-01-46](https://cloud.githubusercontent.com/assets/11840209/7449345/78b5c28e-f234-11e4-9527-11fcc1a24949.png)
as you can see the selected are not the same as others
we need uniformity
thankyou

**Comment by hriziya** [comment]
I still, did not understand, what you are expecting for selected boxes. 

Are you trying to compare inner border of selected box with outer border of other box ?

or please give me your expected layout ..

**Comment by rafdelre** [comment]
ok
1. border has to be present in every icon
2. every icon even elementi has to be 80x80
3. PLEASE HAVE A LOOK AT first screenshot in this issue the one with green borders: leave the red that we have now but please HAVE THE SELECTED ONE be AROUND the box (not inside the box)

thankyou

**Comment by hriziya** [comment]
Done in version 1.0.23

**Comment by rafdelre** [comment]
Thankyou!

**Comment by rafdelre** [comment]
Ok Hitesh Better
BUT PLEASE THE SPACING BETWEEN THE ICONS ARE LARGER
could you go back to distance as in 1.0.22?
thankyou

You really should use layers for this else it will be hard...

**Comment by hriziya** [comment]
Product name below each image causes the spacing looks different I guess. 
see if 1.0.25 has it correctly or we have to make some adjustment.
