### ISSUE TITLE
zone list edit and delete

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#71]
Zone Edit
This should be click of one zone FROM MENU zone List. This will popup same edit box as NEW but with an added button delete.

Zone Delete
Lets make this a confirmation of the above delete.

**Comment by hriziya** [comment]
zone.update and zone.delete API ready ?

**Comment by rafdelre** [comment]
We are working on it

**Comment by sergiostrampelli** [comment]
The APi are ready.  Please read JSON-RPC gDoc

**Comment by hriziya** [comment]
Done

**Comment by rafdelre** [comment]
When pressing delete on a zone it will ask for confirmation but it says "vuoi rimuovere questo profilo." This is relative to profiles NOT zones. It should say "vuoi rimuovere questa zona"

**Comment by rafdelre** [comment]
If not deletable because used, please present a readable error for end user (an exception occurred while....) should be: La Zona è in uso (zone is in use)

thankyou

**Comment by hriziya** [comment]
Fixed in 1.0.30.

**Comment by rafdelre** [comment]
the error is still in "computer jibber"
if possible we need a clean comment like zone in use cannot delete
thankyou

**Comment by hriziya** [comment]
Oh.. Can you please attach screenshot? Thanks
