### ISSUE TITLE
Connection to server crash

### ISSUE THREAD

**Issue by rafdelre** [youppers/app#75]
When app starts, If connection (internet or wifi) is not available with server the app correctly sends us a message with a popup.
This is fine
BUT if one continues to use the app, No message is shown ... try searching a product:
CRASH

**Comment by hriziya** [comment]
Fixed in 1.0.25

**Comment by rafdelre** [comment]
will test

**Comment by sergiostrampelli** [comment]
The App crashes as soon the connection is newly available.

**Comment by hriziya** [comment]
Fixed

**Comment by rafdelre** [comment]
The app still crashes if connection to server is not available

try searching and interrupting wifi.... it will not stop and eventually crash
